language: node_js
node_js:
- '0.12'
before_script:
- npm install -g bower grunt-cli
- gem install sass
- gem install compass
-  sh -c "cd client && npm install && bower install"
services: mongodb
before_deploy:
 -  sh -c "cd client && grunt build --force"
deploy:
  provider: heroku
  api_key:
    secure: B2udZquoOlbJmVNekzXTt6oWWSiTNQ4CESPuXPMDb8CoucNVbzfXnOgvPd4imzwHgHQ2cYTDt48omO4Vc2K1DTPpyEe9ES21RbUQdVuVOITpFfCO8TJRrhrnmrbYHtNGHRpHba1VxH+qpienrWqSkGz5xUDhUF2zmOMLSAmzmNyuFje9NNd2Uoi4kKI7Ae9/Dw3Z2RPs0dDJHU+9wXD7+GvGZnsK7FFtOYpBQQtqh/ZbPaiawpP1Zr/hKSNOorcV4RFZEX3CgADAiV7OeSuXcWWiOtqHJCU7e76aTv3SIxf+8u0waAaAs158FU1gIV8qup5hj8kou2nDEENPRb4LCMvV9jXpPHM4vh6REknWYvrakz0r3zeH+wrqO/K2+WPS0n0aMa5DiSa05AAko+fYRl0BG+zMnZeo0bjSB29LtBH5WuKIbg8mSlVGHs/bnrA88rYBsEiqOLPR/JmEqQjHB3DpBryKRrU346F5y0jeF5pt3JupBJFEK2tjXRHTEA1x/Wn99HVvuhN+4te01bsFwKp4jR6vLieh+pr/XunJQ+vFq5puRavnAZOLxuRhlbuk1hfwarEzpsi8Pf/QxfiW0YY4L/EuNVKyafABpJrO9EtARCN9NCeLwyYraCHYQkpZNYCWGZUChz3mefs/ql9j+byKIJPTh0ioWs2rAG2mOPc=
  on: development
  skip_cleanup: true
