preportsweb:
 build: .
 volumes:
  #mount the app from the current folder
  - /opt/preports:/opt/yukon/node
  #Upload directory for images
  - /opt/preports-data/upload:/var/preports/upload
 links:
  - db
 environment:
  - NODE_ENV=production
  - UPLOAD_DIR=/var/preports/upload
  - MONGODB_DB_HOST=db
  - DISABLE_CAS=true
 ports:
  - "0.0.0.0:3000:3000"
 net: "bridge"
 privileged: true
db:
 image: mongo:3.0.5
 ports:
  - "0.0.0.0:27018:27017"
 volumes:
  - /opt/preports-data/db:/data/db
 privileged: true
